### ISSUE TITLE
Geofence Indicators (circle geofences only) **High Priority**

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/GPS-App#10]
Please use the table rep_geofences / rep_geofences_wv to track geofences.

The table is already created however some fields need to be changed / dropped. See script below. Also find excel spreadsheet that indicates the formula how the geofencing will work.

Everytime the current position of the mechanic comes through the API, additionally to checking the address in Google, also check if the mechanic is in or out the geofences setup on the table.

Depending on the actual location compared to the geofences record the following on a new field called: geofence_notes in the rep_mechanic_coordinates.

If outside all geofences: **Out: All Geofences**
If inside one geofence: **In: SPAR;**
If inside 2 or more geofences: **In: SPAR; In: OFFICE;**

To identify if mechanic is in our out, need to use the geofence lat and long, and see if current distance is greater than radius, if it is, then it is out, otherwise it is in the geofence.

**All distances are tracked in METERS**

[geofenceFormulaSpecs.xlsx](https://github.com/GCSO2/GPS-App/files/176467/geofenceFormulaSpecs.xlsx)

```sql
truncate table rep_geofences;
alter table rep_geofences drop column cus_id;
alter table rep_geofences drop column LAST_INSERT_USERNAME;
alter table rep_geofences drop column LAST_UPDATE_USERNAME;
alter table rep_geofences drop column LAST_INSERT_DATE;
alter table rep_geofences drop column SYSTEM_NOTES;
alter table rep_geofences drop column EMAIL_NOTIFICATION;
alter table rep_geofences drop column TEMP_GEOFENCE_FLAG;
alter table rep_geofences drop column NOTIFY_TECH_IN_FLAG;
alter table rep_geofences drop column NOTIFY_TECH_IN_DATE;
alter table rep_geofences drop column NOTIFY_TECH_OUT_FLAG;
alter table rep_geofences drop column NOTIFY_TECH_OUT_DATE;

alter table rep_geofences add CODE VARCHAR2(25) NOT NULL;
```

**Comment by giovanicani** [comment]
Will discuss tomorrow on the meeting.

**Comment by giovanicani** [comment]
As discussed please work on this on the week of the 21st. Any questions let me know ASAP.

**Comment by giovanicani** [comment]
Added the following column:

```sql
alter table rep_geofences add geo_type VARCHAR2(25) NOT NULL;
ALTER TABLE rep_geofences ADD CONSTRAINT geo_type_ck CHECK (geo_type IN ('SUPPLIER', 'CUSTOMER', 'TRAILCON'));
```

**Comment by d3sqa** [comment]
Prototype is ready and deployed in UAT. Please verify data in geofences table

**Comment by giovanicani** [comment]
**Guys do not update REP_GEOFENCES**

The geofence API needs to update the REP_MECHANIC_COORDINATES on the record that is reported by the mechanic.

Please create the field below:
```sql
ALTER TABLE rep_mechanic_coordinates ADD geofence_notes VARCHAR2(2000);
-- Please also change rep_mechanic_coordinates_wv
```
The IN / OUT notes will be stored on this new field. This field will be linked to the Geofence Remarks on the new GPS screen.

IF GPS_FIX is > 0, then compare lat and long received from mechanic tablet, against the **all the active geofences on the rep_geofences table.** Based on comparison populate geofence_notes.

Thanks!

**Comment by d3sqa** [comment]
1. The Geo fence remarks are now displayed in the grid. See below screenshot:

![image](https://cloud.githubusercontent.com/assets/13255706/13897390/f7b70a4a-edd1-11e5-9ce4-fa83372b639e.png)

2. The geofence API is now updating the REP_MECHANIC_COORDINATES

3. Geofence_notes has also been added to REP_MECHANIC_COORDINATES and REP_MECHANIC_COORDINATES_WV

4. Comparison of latitude and longitude has been done if GPS_FIX

Ready to test in UAT Environment

**Comment by giovanicani** [comment]
1. Please do this small change: only record on the geofence_notes if mobile is inside of the geofence, if he is out don't do anything.

2. Also move the code into production and we will do the tests there.

**Comment by d3sqa** [comment]
Point # 01 has been done.

GPS code has been propagated to production environment

**Comment by giovanicani** [comment]
code has been promoted to prod. Thanks.

Will perform testing and create another ticket if issues are found.
