### ISSUE TITLE
Cloud: Only make it a hyperlink if gps_fix is >= 1

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/GPS-App#11]
if it is waiting for fix, it does not make sense to be a link:

![image](https://cloud.githubusercontent.com/assets/5666297/13928850/cba3b000-ef6d-11e5-8145-b0213abb7015.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Done and ready to test in UAT Environment

![image](https://cloud.githubusercontent.com/assets/13255706/14016273/e7b21d0c-f1e0-11e5-91f8-9376ed6f6bd2.png)

There will be a hyperlink when address is present and the hyperlink will be absent if the address is not present

**Comment by giovanicani** [comment]
please move to PROD.

**Comment by giovanicani** [comment]
done in prod. Thanks!
