### ISSUE TITLE
Cloud: Showing geofence twice for some records

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/GPS-App#13]
See screen shot below, IN: Target is showing more than once.

![image](https://cloud.githubusercontent.com/assets/5666297/13929071/c0cd6d96-ef6e-11e5-9b5c-4e0871b869ba.png)

**Comment by d3sqa** [comment]
It is repeated twice because there is a double insertion in script. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/13942046/047b25a0-f010-11e5-8f3d-02cadd0d862b.png)

**Comment by giovanicani** [comment]
ups! My bad. one record removed thanks!
