### ISSUE TITLE
Cloud: When filtering the timezone issue still occurs

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/GPS-App#14]
See below. Not filtering for the same records work.

![image](https://cloud.githubusercontent.com/assets/5666297/13932393/414d30d2-ef7e-11e5-9213-11bd82636393.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by giovanicani** [comment]
this seems to be resolved, can you please confirm ?

**Comment by giovanicani** [comment]
has been resolved.
