### ISSUE TITLE
Minor Tweak in order to improve precision

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/GPS-App#15]
Please do the following tweaks:

1. Change Address header column to: "Nearest Address"
2. When user clicks on address, **use the lat and long in order to show map**

example: http://maps.google.com/maps?q=43.5441443,-80.3017063

need to show with satellite view

![image](https://cloud.githubusercontent.com/assets/5666297/14188001/bf688c64-f753-11e5-8bfc-45f2576f5f67.png)

**Comment by d3sqa** [comment]
Changes to the map have been done. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/14225958/ba010714-f8ee-11e5-9e67-0b922bd7fc1e.png)

Header has been renamed:

![image](https://cloud.githubusercontent.com/assets/13255706/14225962/cc1ef686-f8ee-11e5-9b80-668884fc35ce.png)

Deployed at production

**Comment by giovanicani** [comment]
great job Thanks!
