### ISSUE TITLE
Logic Tweak to improve GPGGA accuracy

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/GPS-App#6]
When is time to read the GPS coordinates, change the logic so that...

If GPGGA fix is ZERO, then try (loop) at least 10 times to get a GPGGA with fix = 1 if it cannot, then store on the database latest GPGGA info (from the 10th request).

However if after the 3rd time it found a GPGGA with fix = 1, then use that GPGGA.

This logic hopefully will lower the chances of getting GPGGA with 0 fix.

**Comment by giovanicani** [comment]
please update.

**Comment by d3sqa** [comment]
Ready to test

**Comment by giovanicani** [comment]
works.
