### ISSUE TITLE
Documentation to Install on Production

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/GPS-App#7]
Please provide install file and documentation to be installed.

Can we start installing this tomorrow ?

**Comment by tufailzafar** [comment]
GPSAPP has dependency on MRO/Quote APis, can we release with quote on?

**Comment by giovanicani** [comment]
Yes, lets release with Quote. Still need the documentation on how to install the client.

**Comment by d3sqa** [comment]
Please find the attached installation guide for the HuffDuff application

[HuffDuff - Installation Guide V 1.0.docx](https://github.com/GCSO2/GPS-App/files/167093/HuffDuff.-.Installation.Guide.V.1.0.docx)

**Comment by giovanicani** [comment]
Rabia, good job on the doc, can you please add a reference to the parameter file, where users can change the ID and com4.

**Comment by d3sqa** [comment]
@giovanicani, section 3.1 has been added to the document having information regarding the parameter file. Please find the attached document

[HuffDuff - Installation Guide V 1.0.docx](https://github.com/GCSO2/GPS-App/files/168459/HuffDuff.-.Installation.Guide.V.1.0.docx)

**Comment by giovanicani** [comment]
provided. Thanks!
