### ISSUE TITLE
Cloud: GPS Inquiry Screen

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/GPS-App#8]
Build screen below with the following features:

- based on rep_mechanic_coordinates_wv
- needs to have a mechanic selected in order to show records
- Date filter: Today, Yesterday, This Month or Custom (select date range)
- By default only show records with address (fix > 0)
- Show date and time on the user timezone and indicate it beside the time.
- Sorted by date desc
- Menu Button called: GPS Tracking, only the following users to have access for now: gc001, 4-master, Don Andrews

![image](https://cloud.githubusercontent.com/assets/5666297/13607734/85d1b7dc-e51f-11e5-988d-c56569f07de4.png)

**Comment by giovanicani** [comment]
Tufail, please allocate one developer to work on this read only screen.

**Comment by giovanicani** [comment]
As discussed on the meeting today, please allocate a developer for this task

**Comment by d3sqa** [comment]
Work in progress

**Comment by giovanicani** [comment]
please provide update.

**Comment by d3sqa** [comment]
The GPS Inquiry is ready in development environment. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/13768418/ba1d2f6c-ea97-11e5-9950-32c910d132c9.png)

Following is the screenshot of the filter applied. We are still working on the date filter for 'Today, Yesterday, This Month'

![image](https://cloud.githubusercontent.com/assets/13255706/13768616/f17d4684-ea99-11e5-9de2-fd1077f302e7.png)


Rights are also granted to the users: gc001, 4-master

Please note that Don Andrews user is not present in UAT or Development so the rights are not granted to this user yet

**Comment by giovanicani** [comment]
Please do the following changes:

- Column Label: Local(Mobile) Date & Time
- Add Mobile name on the first column instead of username only
- Optimize the size of the column based on its contents
- Geofence Remarks (add column after address)

**Comment by d3sqa** [comment]
Changes have been incorporated. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/13777870/742287f4-ead4-11e5-9f1d-9fa9085532c7.png)

**Comment by giovanicani** [comment]
What does the quick search do ? Doesn't seem to work.

- Can you please make the address a hyperlink that opens Google Maps on a new tab on that address ?
- On the apply filter popup box, on the top add note: "Only 3 months worth of data is available."

**Comment by d3sqa** [comment]
The Addresses are now shown as pointers on google map on a new tab. The verbiage has also been added on the filter and listing displays 3 months records only

Ready to test in UAT Environment

**Comment by giovanicani** [comment]
Yes, address hyper link works thanks!

However filter only reports with address doesn't. See screen shot below. When selected only reports with addresses not null should show.

![image](https://cloud.githubusercontent.com/assets/5666297/13882627/acd8456e-ecfc-11e5-87ff-155010877dd2.png)

**Comment by d3sqa** [comment]
Filter issue has been fixed. When 'Only Reports with Address' is checked, only records that have addresses will be displayed. Ready to test in UAT

**Comment by giovanicani** [comment]
1. Why now it only shows username, and not the name like it was before ?

2. Please make the geofence column 30% wider.

Move the screen to production and only give access to 
Don Andrews,
Giovani Cani
Claude Beland
4-master
Gary Chan

**Comment by d3sqa** [comment]
Point # 01 and 02 have been done

Also, the code has been propagated to production environment. Rights to the following users have been granted:

Don Andrews
Giovani Cani
Claude Beland
4-master
Gary Chan

**Comment by giovanicani** [comment]
works.
